### ISSUE TITLE
PyPI sdist fails because VERSION is missing

### ISSUE THREAD

**Issue by jayvdb** [sradc/magic-timer#1]

**Comment by sradc** [comment]
Thanks @jayvdb.

Solution for now is to stop using VERSION file, and put version directly in setup.py. 75349f2432cde731042d0dde070d31a446f1e294

Cause of problem:

"When building a source distribution for your package, by default only a minimal set of files are included."

[https://packaging.python.org/guides/using-manifest-in/](https://packaging.python.org/guides/using-manifest-in/)

In order to keep using VERSION file, would add a MANIFEST.in 

(a relevant issue: https://github.com/ethereum/eth-rlp/issues/6).
